add: add proxies option to pass traffic through burp suite
nikitastupin/clairvoyance pull request #36
Opened 2022-07-08 11:57 UTC by arthur4ires

Hi, hope you are well :)

Thanks a lot for the tool, it contributes a modification to watch traffic using BurpSuite.

The example command is as follows:

```
python3 -m clairvoyance -vv -o output -w google-10000-english.txt -p http://127.0.0.1:8080 -k https://site/graphql
```

2022-07-08 15:14 UTC, nikitastupin commented on clairvoyance/__main__.py
> +        help="Use a proxy such as BurpSuite to debug requests.",
```suggestion
        help="Use the specified HTTP proxy (e.g. BurpSuite to debug requests). This parameter is passed to https://requests.readthedocs.io/en/latest/user/advanced/#proxies.",
```

2022-07-08 15:15 UTC, nikitastupin commented on clairvoyance/__main__.py
> +        required=False,
```suggestion
        metavar="[protocol://]host[:port]",
```

2022-07-08 15:16 UTC, nikitastupin commented on clairvoyance/__main__.py
> +        required=False,
The `required` parameter is implicitly set to `False` here. Also, added `metavar` to mimic `curl`'s man. What do you think about that?

2022-07-08 15:19 UTC, nikitastupin commented on clairvoyance/__main__.py
> +        default=False,
```suggestion
        default=None,
```

2022-07-08 15:20 UTC, nikitastupin commented on clairvoyance/__main__.py
> +        default=False,
The `None` value passed to [`proxies`](https://requests.readthedocs.io/en/latest/user/advanced/#proxies) works as if there is no proxy. We can simplify code by leveraging that.

2022-07-08 15:21 UTC, arthur4ires commented
For me it's ok, thank you for the reply :)

2022-07-08 15:24 UTC, nikitastupin commented on clairvoyance/__main__.py
> +
Can be simplified (see the comment above)

2022-07-08 15:24 UTC, nikitastupin commented on clairvoyance/graphql.py
> +
Can be simplified also

2022-07-08 15:25 UTC, nikitastupin commented on clairvoyance/oracle.py
> +
Can be simplified - I don't think we need `if-else` here

2022-07-08 15:26 UTC, nikitastupin requested changes
Hey @arthur4ires!

Thank you for the contribution 😃 

I've left a few comments I'd like to address or discuss before merging.

2022-07-08 15:37 UTC, arthur4ires commented
Yes, I will make the changes :)

2022-07-08 16:54 UTC, arthur4ires commented
Hello @nikitastupin , I accepted your modifications, thanks for the suggestions in the code!

2022-07-09 07:56 UTC, nikitastupin commented on clairvoyance/graphql.py
> +def post(url, data=None, json=None, proxies=None, **kwargs):
I suppose the `proxies` can be passed as part of `**kwargs` so we don't need the explicit `proxies` parameter.

2022-07-09 07:57 UTC, nikitastupin commented on clairvoyance/__main__.py
> +
```suggestion
    config.proxies = {"http": args.proxies, "https": args.proxies} if args.proxies else None
        
```

2022-07-09 07:58 UTC, nikitastupin commented on clairvoyance/graphql.py
> +def post(url, data=None, json=None, proxies=None, **kwargs):
The same way as `verify` is passed

2022-07-09 07:59 UTC, nikitastupin commented on clairvoyance/oracle.py
> +
There are also other `.post(...)` calls, we should address them aswell

2022-07-09 08:00 UTC, nikitastupin requested changes
Thanks! I think we can further simplify the code and also add proxies to all requests. Would you be willing to make the changes I've requested in comments?

2022-12-29 04:29 UTC, zeroc00I commented
Sup folks
Some updates here?

2022-12-29 07:59 UTC, nikitastupin commented
Hey @zeroc00I,

I believe you can use the `HTTP_PROXY` & `HTTPS_PROXY` environment variables to proxy clairvoyance https://requests.readthedocs.io/en/latest/user/advanced/#proxies

2023-02-14 15:56 UTC, QuentinN42 commented
Hey @arthur4ires @zeroc00I at Escape, we are working to secure the graphql api. We forked this repo a week ago and I implemented this feature there.

https://github.com/Escape-Technologies/ClairvoyanceNext

2023-02-14 16:05 UTC, arthur4ires commented
Hi there, thanks a lot for the update :)

2023-02-14 16:05 UTC, closed without merging